### PR TITLE
[WEB-9204] Implement Ecom journey tests: Create a cart with products 

### PR DESCRIPTION
**Pull request by ZhuchenLiu**
- Add `POST create cart` endpoint

### CODE REVIEW

**Review by clea51 — APPROVED** [review]
I trust you, Zhuchen!

**Review by clea51 — APPROVED** [review]
all good

**Review by gabrieljo — APPROVED** [review]
Nice work! @ZhuchenLiu

**Review by kiko-serato — APPROVED** [review]

**Review by takayuki-serato — APPROVED** [review]
Nice one @ZhuchenLiu !

**Pull request merged**
